#!/usr/bin/env python3
"""
Debug Observation Spaces - Compare Genesis vs LocoMujoco Skeleton Observations (FIXED VERSION)

This script analyzes the exact observation structures from both:
1. Genesis SkeletonHumanoidEnv observations (_get_observations)
2. LocoMujoco expert trajectory observations 
3. Expert observations generated by data_bridge for GAIL training

Purpose: Identify observation space mismatches that could cause GAIL training issues.
"""

import torch
import numpy as np
import sys
import os

# Import paths
sys.path.append('/home/ez/Documents/Genesis/genesis_loco')
sys.path.append('/home/ez/Documents/loco-mujoco')

import genesis as gs
from environments.skeleton_humanoid import SkeletonHumanoidEnv
from integration.data_bridge import LocoMujocoDataBridge


def analyze_genesis_observations():
    """Analyze Genesis SkeletonHumanoidEnv observation structure"""
    print("=" * 60)
    print("GENESIS SKELETON HUMANOID OBSERVATIONS")
    print("=" * 60)
    
    try:
        # Initialize Genesis
        gs.init(backend=gs.gpu)
        
        # Create environment
        env = SkeletonHumanoidEnv(
            num_envs=1,
            episode_length_s=5.0,
            dt=0.02,
            use_box_feet=True,
            show_viewer=False
        )
        
        print(f"Environment created successfully:")
        print(f"  - num_observations: {env.num_observations}")
        print(f"  - num_actions: {env.num_actions}")
        print(f"  - motors_dof_idx: {len(env.motors_dof_idx)} indices")
        print(f"  - joint_names: {len(env.joint_names)} joints")
        print(f"  - use_box_feet: {env.use_box_feet}")
        
        # Print motor DOF indices for reference
        print(f"  - motors_dof_idx list: {env.motors_dof_idx}")
        
        # Reset and get observations
        obs, _ = env.reset()
        print(f"\nObservation tensor:")
        print(f"  - Shape: {obs.shape}")
        print(f"  - Device: {obs.device}")
        print(f"  - Dtype: {obs.dtype}")
        
        # Analyze observation components based on _get_observations implementation
        print(f"\nObservation structure breakdown (from _get_observations):")
        
        # Component 1: Root Z position (1D)
        root_z = env.root_pos[:, 2:3]  # z position
        print(f"  1. Root Z position: {root_z.shape} = {root_z.shape[1]} values")
        
        # Component 2: Root quaternion (4D) 
        root_quat = env.root_quat
        print(f"  2. Root quaternion: {root_quat.shape} = {root_quat.shape[1]} values")
        
        # Component 3: Controlled joint positions
        local_dof_indices = [idx - env.robot.dof_start for idx in env.motors_dof_idx]
        joint_pos = env.robot.get_dofs_position(local_dof_indices)
        print(f"  3. Joint positions: {joint_pos.shape} = {joint_pos.shape[1]} values")
        
        # Component 4: Root linear velocity (3D)
        root_lin_vel = env.root_lin_vel
        print(f"  4. Root linear velocity: {root_lin_vel.shape} = {root_lin_vel.shape[1]} values")
        
        # Component 5: Root angular velocity (3D)
        root_ang_vel = env.root_ang_vel
        print(f"  5. Root angular velocity: {root_ang_vel.shape} = {root_ang_vel.shape[1]} values")
        
        # Component 6: Controlled joint velocities
        joint_vel = env.robot.get_dofs_velocity(local_dof_indices)
        print(f"  6. Joint velocities: {joint_vel.shape} = {joint_vel.shape[1]} values")
        
        # Total expected
        expected_total = 1 + 4 + joint_pos.shape[1] + 3 + 3 + joint_vel.shape[1]
        print(f"\nExpected total: {expected_total}")
        print(f"Actual total: {obs.shape[1]}")
        print(f"Match: {expected_total == obs.shape[1]}")
        
        print(f"\nSample observation values (first environment):")
        print(f"  - Root Z: {root_z[0].item():.4f}")
        print(f"  - Root quat: [{root_quat[0, 0].item():.4f}, {root_quat[0, 1].item():.4f}, {root_quat[0, 2].item():.4f}, {root_quat[0, 3].item():.4f}]")
        print(f"  - First 5 joint pos: {joint_pos[0, :5].tolist()}")
        print(f"  - Root lin vel: {root_lin_vel[0].tolist()}")
        print(f"  - Root ang vel: {root_ang_vel[0].tolist()}")
        print(f"  - First 5 joint vel: {joint_vel[0, :5].tolist()}")
        
        return {
            'env': env,
            'obs_shape': obs.shape,
            'obs_sample': obs[0].clone(),
            'components': {
                'root_z': root_z[0].clone(),
                'root_quat': root_quat[0].clone(), 
                'joint_pos': joint_pos[0].clone(),
                'root_lin_vel': root_lin_vel[0].clone(),
                'root_ang_vel': root_ang_vel[0].clone(),
                'joint_vel': joint_vel[0].clone()
            }
        }
        
    except Exception as e:
        print(f"❌ Genesis analysis failed: {e}")
        import traceback
        traceback.print_exc()
        return None


def analyze_locomujoco_skeleton():
    """Analyze LocoMujoco SkeletonTorque observation structure"""
    print("\n" + "=" * 60)
    print("LOCOMUJOCO SKELETON TORQUE OBSERVATIONS")
    print("=" * 60)
    
    try:
        # Import LocoMujoco components
        from loco_mujoco.task_factories.imitation_factory import ImitationFactory
        from loco_mujoco.task_factories.dataset_confs import DefaultDatasetConf
        
        # Create LocoMujoco environment
        loco_env = ImitationFactory.make(
            "SkeletonTorque",
            default_dataset_conf=DefaultDatasetConf(["walk"])
        )
        
        print(f"LocoMujoco environment created:")
        print(f"  - Environment type: {type(loco_env)}")
        print(f"  - Model type: {type(loco_env).__name__}")
        print(f"  - Model nq (positions): {loco_env.model.nq}")
        print(f"  - Model nv (velocities): {loco_env.model.nv}")
        
        # Get initial observation
        loco_obs = loco_env.reset()
        print(f"\nLocoMujoco observation:")
        print(f"  - Shape: {loco_obs.shape}")
        print(f"  - Dtype: {loco_obs.dtype}")
        print(f"  - Expected obs size (from docs): 65 (5 root + 27 joints + 6 root_vel + 27 joint_vel)")
        print(f"  - Actual obs size: {len(loco_obs)}")
        
        # Based on SkeletonTorque documentation, parse observation structure:
        print(f"\nLocoMujoco observation structure (based on documentation):")
        print(f"  - Indices 0-4: q_root (FreeJointPosNoXY) = 5 values")
        print(f"  - Indices 5-31: Joint positions (27 joints) = 27 values") 
        print(f"  - Indices 32-37: dq_root (FreeJointVel) = 6 values")
        print(f"  - Indices 38-64: Joint velocities (27 joints) = 27 values")
        print(f"  - Total: 5 + 27 + 6 + 27 = 65 observations")
        
        # Sample values
        print(f"\nSample LocoMujoco observation values:")
        print(f"  - Root pos (0-4): {loco_obs[0:5]}")
        print(f"  - First 5 joint pos (5-9): {loco_obs[5:10]}")
        print(f"  - Root vel (32-37): {loco_obs[32:38]}")
        print(f"  - First 5 joint vel (38-42): {loco_obs[38:43]}")
        
        # Analyze trajectory data structure
        traj = loco_env.th.traj
        print(f"\nLocoMujoco trajectory structure:")
        print(f"  - qpos shape: {traj.data.qpos.shape}")
        print(f"  - qvel shape: {traj.data.qvel.shape}")
        print(f"  - Joint names: {len(traj.info.joint_names)} joints")
        print(f"  - Frequency: {traj.info.frequency} Hz")
        
        # Sample trajectory state
        sample_qpos = traj.data.qpos[0]
        sample_qvel = traj.data.qvel[0] 
        print(f"\nSample trajectory state (timestep 0):")
        print(f"  - qpos shape: {sample_qpos.shape}")
        print(f"  - qvel shape: {sample_qvel.shape}")
        print(f"  - Root pos: {sample_qpos[:3]}")
        print(f"  - Root quat: {sample_qpos[3:7]}")
        print(f"  - First 5 joint pos: {sample_qpos[7:12]}")
        
        # Check joint name mapping if available
        if hasattr(traj.info, 'joint_name2ind_qpos'):
            print(f"\nJoint name to qpos index mapping available:")
            sample_joints = list(traj.info.joint_names)[:5]
            for joint_name in sample_joints:
                if joint_name in traj.info.joint_name2ind_qpos:
                    qpos_idx = traj.info.joint_name2ind_qpos[joint_name]
                    print(f"  - {joint_name}: qpos index {qpos_idx}")
                else:
                    print(f"  - {joint_name}: not found in mapping")
        
        return {
            'env': loco_env,
            'obs_shape': loco_obs.shape,
            'obs_sample': loco_obs.copy(),
            'traj': traj,
            'sample_qpos': sample_qpos,
            'sample_qvel': sample_qvel
        }
        
    except Exception as e:
        print(f"❌ LocoMujoco analysis failed: {e}")
        import traceback
        traceback.print_exc()
        return None


def analyze_expert_observation_conversion(genesis_data, loco_data):
    """Analyze how expert trajectory states are converted to Genesis observations"""
    print("\n" + "=" * 60) 
    print("EXPERT OBSERVATION CONVERSION ANALYSIS")
    print("=" * 60)
    
    if genesis_data is None or loco_data is None:
        print("❌ Cannot analyze conversion - missing data")
        return None
        
    try:
        # Create data bridge
        data_bridge = LocoMujocoDataBridge(genesis_data['env'])
        
        # Load trajectory
        success = data_bridge.load_trajectory("walk")
        if not success:
            print("❌ Failed to load trajectory in data bridge")
            return None
            
        print(f"Data bridge created successfully:")
        print(f"  - Trajectory length: {data_bridge.trajectory_length}")
        print(f"  - Trajectory frequency: {data_bridge.trajectory_frequency}")
        
        # Get trajectory state conversion
        timestep = 0
        converted_state = data_bridge.get_trajectory_state(timestep)
        
        if converted_state is None:
            print("❌ Failed to convert trajectory state")
            return None
            
        print(f"\nConverted trajectory state (timestep {timestep}):")
        print(f"  - dof_pos shape: {converted_state['dof_pos'].shape}")
        print(f"  - dof_vel shape: {converted_state['dof_vel'].shape}")  
        print(f"  - root_pos: {converted_state['root_pos']}")
        print(f"  - root_quat: {converted_state['root_quat']}")
        print(f"  - root_lin_vel: {converted_state['root_lin_vel']}")
        print(f"  - root_ang_vel: {converted_state['root_ang_vel']}")
        
        # Apply state to Genesis environment and get observation
        env_ids = torch.tensor([0], device=genesis_data['env'].device)
        data_bridge.apply_trajectory_state(converted_state, env_ids)
        
        # Get observation after applying trajectory state
        expert_obs = genesis_data['env']._get_observations()
        
        print(f"\nExpert observation (from applied trajectory state):")
        print(f"  - Shape: {expert_obs.shape}")
        print(f"  - Sample values: {expert_obs[0, :10].tolist()}")
        
        # Compare with policy observation structure
        print(f"\nComparison with Genesis policy observations:")
        genesis_obs = genesis_data['obs_sample']
        print(f"  - Genesis policy obs shape: {genesis_obs.shape}")
        print(f"  - Expert obs shape: {expert_obs[0].shape}")
        print(f"  - Shapes match: {genesis_obs.shape == expert_obs[0].shape}")
        
        if genesis_obs.shape == expert_obs[0].shape:
            # Compare value ranges
            policy_range = f"[{genesis_obs.min():.4f}, {genesis_obs.max():.4f}]"
            expert_range = f"[{expert_obs[0].min():.4f}, {expert_obs[0].max():.4f}]"
            print(f"  - Policy value range: {policy_range}")
            print(f"  - Expert value range: {expert_range}")
            
            # Check for significant differences
            abs_diff = torch.abs(genesis_obs - expert_obs[0])
            mean_diff = abs_diff.mean().item()
            max_diff = abs_diff.max().item()
            print(f"  - Mean absolute difference: {mean_diff:.6f}")
            print(f"  - Max absolute difference: {max_diff:.6f}")
        else:
            print("  - ❌ Shape mismatch detected!")
            
        return {
            'converted_state': converted_state,
            'expert_obs': expert_obs[0].clone(),
            'shapes_match': genesis_obs.shape == expert_obs[0].shape
        }
        
    except Exception as e:
        print(f"❌ Conversion analysis failed: {e}")
        import traceback
        traceback.print_exc()
        return None


def compare_joint_mappings(genesis_data, loco_data):
    """Compare joint mappings between Genesis and LocoMujoco"""
    print("\n" + "=" * 60)
    print("JOINT MAPPING COMPARISON")
    print("=" * 60)
    
    if genesis_data is None or loco_data is None:
        print("❌ Cannot compare mappings - missing data")
        return
        
    try:
        # Genesis joint information
        genesis_joints = set(genesis_data['env'].joint_names)
        genesis_motor_count = len(genesis_data['env'].motors_dof_idx)
        
        # LocoMujoco joint information  
        loco_joints = set(loco_data['traj'].info.joint_names)
        
        print(f"Genesis joints ({len(genesis_joints)}):") 
        for joint in sorted(genesis_joints):
            print(f"  - {joint}")
            
        print(f"\nLocoMujoco joints ({len(loco_joints)}):")
        for joint in sorted(loco_joints):
            print(f"  - {joint}")
            
        print(f"\nGenesis controllable motors: {genesis_motor_count}")
        print(f"Genesis motors_dof_idx: {genesis_data['env'].motors_dof_idx}")
        
        # Find common and missing joints
        common_joints = genesis_joints.intersection(loco_joints)
        genesis_only = genesis_joints - loco_joints
        loco_only = loco_joints - genesis_joints
        
        print(f"\nJoint mapping analysis:")
        print(f"  - Common joints: {len(common_joints)}/{len(loco_joints)}")
        print(f"  - Genesis-only joints: {len(genesis_only)}")
        print(f"  - LocoMujoco-only joints: {len(loco_only)}")
        print(f"  - Genesis controllable motors: {genesis_motor_count}")
        
        if genesis_only:
            print(f"\n  Genesis-only joints:")
            for joint in sorted(genesis_only):
                print(f"    - {joint}")
                
        if loco_only:
            print(f"\n  LocoMujoco-only joints:")
            for joint in sorted(loco_only):
                print(f"    - {joint}")
        
        # Check coverage
        coverage = len(common_joints) / len(loco_joints) if loco_joints else 0
        print(f"\nJoint coverage: {coverage:.1%}")
        
        if coverage < 0.9:
            print("  ⚠️  Warning: Low joint coverage may cause training issues")
        else:
            print("  ✅ Good joint coverage")
            
    except Exception as e:
        print(f"❌ Joint mapping comparison failed: {e}")
        import traceback
        traceback.print_exc()


def main():
    """Main debugging function"""
    print("🔍 OBSERVATION SPACE DEBUGGING SCRIPT (FIXED)")
    print("Analyzing Genesis vs LocoMujoco skeleton observation structures...\n")
    
    # Analyze Genesis observations
    genesis_data = analyze_genesis_observations()
    
    # Analyze LocoMujoco observations  
    loco_data = analyze_locomujoco_skeleton()
    
    # Compare joint mappings
    compare_joint_mappings(genesis_data, loco_data)
    
    # Analyze expert observation conversion
    conversion_data = analyze_expert_observation_conversion(genesis_data, loco_data)
    
    # Summary
    print("\n" + "=" * 60)
    print("DEBUGGING SUMMARY")
    print("=" * 60)
    
    if genesis_data and loco_data:
        print(f"✅ Successfully analyzed both observation spaces")
        print(f"  - Genesis obs shape: {genesis_data['obs_shape']}")
        print(f"  - LocoMujoco obs shape: {loco_data['obs_shape']}")
        
        # Key differences
        genesis_obs_size = genesis_data['obs_shape'][1]
        loco_obs_size = len(loco_data['obs_sample'])
        
        print(f"\n🔍 KEY FINDINGS:")
        print(f"  - Genesis observation size: {genesis_obs_size}")
        print(f"  - LocoMujoco observation size: {loco_obs_size}")
        print(f"  - Size difference: {genesis_obs_size - loco_obs_size}")
        
        if genesis_obs_size != loco_obs_size:
            print(f"  - ❌ OBSERVATION SIZE MISMATCH DETECTED!")
            print(f"  - This is likely causing GAIL discriminator issues")
        else:
            print(f"  - ✅ Observation sizes match")
        
        if conversion_data:
            if conversion_data['shapes_match']:
                print(f"  - ✅ Expert/Policy observation shapes match")
            else:
                print(f"  - ❌ Expert/Policy observation shape MISMATCH")
            print(f"  - Expert obs shape: {conversion_data['expert_obs'].shape}")
    else:
        print(f"❌ Analysis incomplete - check error messages above")
    
    print("\n🎯 Next steps:")
    print("  1. Check for observation shape mismatches")
    print("  2. Verify joint mapping coverage")  
    print("  3. Compare value ranges between expert and policy observations")
    print("  4. Test GAIL discriminator with matched observation shapes")


if __name__ == "__main__":
    main()